### PR TITLE
完成task4 5 6 move_game move_swap Dapp-kit SDK PTB ✅

### PR DESCRIPTION
**Pull request by Maqihao01**

### CODE REVIEW

**Comment by Maqihao01** [comment]
## Dapp-kit SDK PTB 的交易hash

[J3RTijmy42AudV1Af784jaoCUCSRJCxCVxqq3Zee9jNV](https://suivision.xyz/txblock/J3RTijmy42AudV1Af784jaoCUCSRJCxCVxqq3Zee9jNV)

**Review by uvd — APPROVED** [review]
https://suivision.xyz/txblock/DJd6NEgBp8ApJiCQbFLbuAfrx8VTRViMB8x4kkDZLirv

**Review by uvd — APPROVED** [review]
https://suivision.xyz/txblock/DWXEVkatXFQQJGhR179j7kcxf1f5kHGvLNm3tN2m9NHW

**Review by uvd — APPROVED** [review]
https://suivision.xyz/txblock/ASqyNj9rq9p2ERA9ASDGvm1Snyj7HT3Dq8SmxWk7vnZM

**Pull request merged**
