### PR TITLE
finished task1 2 3 4 5 6

### PR DESCRIPTION
**Pull request by ReiType0**
##   01 hello move  
- [x] package id: [0xb34e3f93b3aee55c3726ab9ff4d73ee6f623c4ed29832a78d1726a0a8afc548f](https://testnet.suivision.xyz/package/0xb34e3f93b3aee55c3726ab9ff4d73ee6f623c4ed29832a78d1726a0a8afc548f)

check the hello object at [0x4e60c7a6c981a8c4632b927e7b0abca02e468963e888b42f405cbef9a9caf428](https://testnet.suivision.xyz/object/0x4e60c7a6c981a8c4632b927e7b0abca02e468963e888b42f405cbef9a9caf428)

### CODE REVIEW

**Comment by ReiType0** [comment]
##   04 Move Game
`mainnet`
- [x] game package id : [0xef0b128db4bb4393c8e2725cdf8f6ef3ff0669247ea7f51cdf4e7bf8019dea56](https://suivision.xyz/package/0xef0b128db4bb4393c8e2725cdf8f6ef3ff0669247ea7f51cdf4e7bf8019dea56)
- [x] call game hash : [GW8mXZEVHwDqggRUMecfGbrFUgFV8XCj6YiqD7W7wkFr](https://suivision.xyz/txblock/GW8mXZEVHwDqggRUMecfGbrFUgFV8XCj6YiqD7W7wkFr)

**Comment by ReiType0** [comment]
##   05 Move Swap
- [x] swap package id : [0x0be58ebe0778486302657e16d516ec3501a0318dedf8d37f12ae0eea1867d721](https://suivision.xyz/package/0x0be58ebe0778486302657e16d516ec3501a0318dedf8d37f12ae0eea1867d721)
- [x] call swap hash: [DKUN81sE4Lbc6MXGpC9yPAuSs9yPEEKB3HiwjPzZ9EJF](https://suivision.xyz/txblock/DKUN81sE4Lbc6MXGpC9yPAuSs9yPEEKB3HiwjPzZ9EJF)

思路是，先将task5的swap上链，使用task2中的coin和faucet铸造币，使用它们调用task5的swap中的方法创造pool，这时候再铸造一枚coin，调用task5的swap中的方法交换得到faucet

**Comment by ReiType0** [comment]
##   06 SDK PTB
- [x] save hash : [CqyMbCoUoWFJFu4BB6o1Fp4hXWiqA9FjSC6osDx1NoDt](https://suivision.xyz/txblock/CqyMbCoUoWFJFu4BB6o1Fp4hXWiqA9FjSC6osDx1NoDt)

**Review by uvd — APPROVED** [review]
https://suivision.xyz/txblock/9kKdRzEDQAxSffP6XBNh28XkA89LSLmWcRat1ngsGki3

**Review by uvd — APPROVED** [review]
https://suivision.xyz/txblock/CTy3h7kuH1DZRzUtqqV2gJQ2FaEL7hAyaaV3Wh5fLkPi

**Comment by Euraxluo** [comment]
leaked pk

**Pull request merged**
